### ISSUE TITLE
sourcermaps

### ISSUE THREAD

**Issue by robsonsobral** [wpfpizicai/gulp-md5-plus#12]
Hi!

Thank you for the module. It's very useful.

I'm sorry, but I'm having a hard time with sourcemaps. They're being renamed, but not the references to them.

Can you, please, update the sample usage with how to proceed in this case?

Thank you!

**Comment by wpfpizicai** [comment]
update to the latest version

**Comment by robsonsobral** [comment]
I'm sorry, but I couldn't find a way to make it work. Both the file and the sourcemap get renamed, but the reference to the sourcemap remains the original: ` //# sourceMappingURL=application.js.map`.

How can I edit the reference to the sourcemap too?

I tried `md5(10, [templatesPath + '/**/*.html', destPath + '/**/*.js'])`, being `destPath` the folder where the renamed JS are saved.

Thank you.
