### ISSUE TITLE
Option 'dirLevel' has a bug with Windows

### ISSUE THREAD

**Issue by rdshoep** [wpfpizicai/gulp-md5-plus#13]
I hava some files like this:

```
build/css/main.min.css
build/js/app.min.js
```

then I put them in html files:

```
<link href="//cdn.bootcss.com/css/main.min.css" rel="stylesheet">
<link href="/css/main.min.css" rel="stylesheet">
<script src="/js/app.min.js" type="text/javascript"></script>
```

I want replace `app.min.js` and `main.min.css`, so I set `option.dirLevel = 1`.
It works fine in Mac and other Linux platform, but it's broken in Windows.

I take some logs, then I found the secrect.
Mac & Linux:
    use `js/app.min.js` to replace
Windows:
    use `js\app.min.js` to replace

So, how to resolve? add a option `sep` to replace?

**Comment by rdshoep** [comment]
I close this issue.

create a new with a pull request.[#14](https://github.com/wpfpizicai/gulp-md5-plus/pull/14)

**Comment by rainboweast** [comment]
same issue.+1

**Comment by rainboweast** [comment]
rdshoep's commited files work well

**Comment by wpfpizicai** [comment]
thanks for @david-eddy.  It has released to the latest version!
