### ISSUE TITLE
我的天啊，我调试longlonglonglongtime，不知道哪里出错了

### ISSUE THREAD

**Issue by JoeBBChen** [wpfpizicai/gulp-md5-plus#15]
![image](https://cloud.githubusercontent.com/assets/12586787/19770113/9aacda14-9c90-11e6-9b83-6029a6e991cd.png)
求搭救， 为什么html的路径没有替换的？？？

**Comment by fxioi** [comment]
在 github 提问最好好好说话（用书面语），尽量用英语，你认为老外都能看懂中文么？

**Comment by JoeBBChen** [comment]
对不起。我只是调试了一天还是没发现问题太激动了所以才这样表述。

**Comment by fxioi** [comment]
@JoeBBChen 不用和我「对不起」额...
把 issue 改成英文就好啦~
我只是查资料路过的~XD
