### ISSUE TITLE
HTML code reference img

### ISSUE THREAD

**Issue by cat-kun** [wpfpizicai/gulp-md5-plus#18]
If the HTML code has a reference to the IMG image, how to make img plus MD5 stamp
```html
<div class="qrcode"><img src="images/qrcode2.png" alt=""></div>
```

**Comment by wpfpizicai** [comment]
`gulp.src('./source/img/**/*')
        .pipe(md5(10 ,['./output/css/*.css','./output/*.html'],{
        	dirLevel : 1
        }))
        .pipe(gulp.dest('./output/img/'));`
