### ISSUE TITLE
v0.2.5 still have a little problem

### ISSUE THREAD

**Issue by cloudyan** [wpfpizicai/gulp-md5-plus#20]
#8 problem is unfixed，still have a little problem. different path and different file,but replaced as a last file

```
<link rel="icon" type="image/png" href="//static.doweidu.com/static/iqg/favicon_9d14bbe40c.png">
<link rel="icon" type="image/png" href="//static.doweidu.com/static/hsq/favicon_9d14bbe40c.png">
```

should be

```
<link rel="icon" type="image/png" href="//static.doweidu.com/static/iqg/favicon_01113cdd06.png">
<link rel="icon" type="image/png" href="//static.doweidu.com/static/hsq/favicon_9d14bbe40c.png">
```

**Comment by rdshoep** [comment]
you can set `dirLevel:1` to solve this problem

**Comment by cloudyan** [comment]
@rdshoep  @dirLevel can't auto

DirLevel should not be manually specified, but should be read automatically, consistent with the actual path, and why? Because there are various possible paths, there are some differences between the first layer, and some of the third layers are different. At the same time, some files are only on the first floor and are not suitable when they are set up in different layers

has error like this

```
set dirLevel=1,is OK,
//static.doweidu.com/static/iqg/favicon_01113cdd06.png
//static.doweidu.com/static/hsq/favicon_9d14bbe40c.png

but this need dirLevel = 3, above will error
//static.doweidu.com/static/iqg/images/logo_fdfe8f30f2.png
//static.doweidu.com/static/hsq/images/logo_fdfe8f30f2.png
```

**Comment by rdshoep** [comment]
Yeah. Set dirLevel to be auto is smart mind. 

I think DirLevel can support manual mode and auto mode, auto mode is default kind.
like:
```js
dirLevel: 'auto' //default
dirLevel: 2 //also support manual path
```

Supplement：
```js
gulp.src('your/css/folder/**/*.png')
    .pipe(md5(10, files, {dirLevel: 1}))
    .pipe(md5(10, files, {dirLevel: 3}))
    .pipe(gulp.dest('your/dest/path'))
```
you can solve your problem. But if the different layers have the same name, it will be not OK.
