### ISSUE TITLE
You may need to republish the version on `npm`

### ISSUE THREAD

**Issue by Amery2010** [wpfpizicai/gulp-md5-plus#22]
At present you released the version at `npm` is a wrong version, I hope you can update once again, thank you.

You need the `jsonfile` module, but you did not write it into the` package.json`

**Comment by wpfpizicai** [comment]
It's done!

**Comment by ipoly** [comment]
I think `jsonfile` should be in `dependencies`?
Because I still get a `Error: Cannot find module 'jsonfile'` after update.

**Comment by robsonsobral** [comment]
https://github.com/wpfpizicai/gulp-md5-plus/issues/23
