### ISSUE TITLE
Issue with similar filename strings

### ISSUE THREAD

**Issue by okiii** [wpfpizicai/gulp-md5-plus#5]
I have this CSS code:

```
@font-face {
    font-family: "icons";
    src: url('/fonts/icons.eot');
    src: url('/fonts/icons.eot?#iefix') format('eot'),
        url('/fonts/icons.woff2') format('woff2'),
        url('/fonts/icons.woff') format('woff'),
        url('/fonts/icons.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}
```

See how `icons.woff` and `icons.woff2` are the same except for the 2 at the end? At the moment both are being replaced with the same thing:

```
url(/fonts/icons_c5c3b.woff2) format("woff2"),
url(/fonts/icons_c5c3b.woff) format("woff"),
```

The expected result is that both are treated as separate things:

```
url(/fonts/icons_12db4.woff2) format("woff2"),
url(/fonts/icons_c5c3b.woff) format("woff"),
```

Looks like the string replacing regex might need to be tweaked. I'll have a go, but I'm no js wizz. Or maybe is there some hack I could do?

**Comment by wpfpizicai** [comment]
Thanks for your advise,It's has fixed;
