### ISSUE TITLE
Getting generated filenames

### ISSUE THREAD

**Issue by MentalGear** [wpfpizicai/gulp-md5-plus#7]
Hi there,
First off, let me say thank you so much for this plug-in !
It is exactly what I was looking for, and so easy and elegant to implement.
Before this plugin, I fiddled with "specified" cache busting plugins like gulp-rev or gulp-bust, and a few others. But none of them really worked as they should, and definitely not as uncomplicated as yours !

Well, enough of the praise and to my issue:
I need to modify the linked references in a .css file that itself is generated by gulp-md5-plus.
As the file is generated in the process, I can not exactly specify it in the parameter.

Is it possible to get the generated filename of a md5-plus action in order to use it later on in the task?

For example:

``` javascript
var new_main_css_filename = "";

gulp.task("style", function() {
    return gulp.src( Source.style )
        .pipe( md5(10, "./" + output_folder + '/index.html') )
            .on("done", function(event) {
                new_main_css_filename = event.filename[1];
            }
        )
        .pipe( gulp.dest(output_folder + "/css/") )
});

gulp.task("image_assets", function() {
    return gulp.src( Source.other_assets , { cwd: source_folder } )

        .pipe( md5(10, "./" + output_folder + "css/" + new_main_css_filename ) )

        .pipe( gulp.dest(output_folder) )
});

```

**Comment by wpfpizicai** [comment]
Thanks for your praise; As I know, the mechanism of gulp has not provided api 'on' in the process;
for your issue:Usually,we md5 img file and change its name in the css file; then md5 css file and change its name in the html file; notes : gulp.task('style',['image'],function(){});this can make style task run after image task;
